# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assignments.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(610, 400)
        Dialog.setMinimumSize(QtCore.QSize(610, 400))
        Dialog.setMaximumSize(QtCore.QSize(610, 400))
        Dialog.setStyleSheet("background-color: #fcfeff")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 590, 310))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(220, 340, 160, 40))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Assignments"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Задание 1</span><span style=\" font-size:10pt;\">. Сделать датчик случайных чисел, который генерирует “0” или “1” с заданными вероятностями (можно взять стандартный датчик, выдающий числа на промежутке [0;1] и рассмотреть границу - число p из этого промежутка; тогда если выпавшее число меньше p выбирается “0”, иначе “1”; нетрудно понять, что “0” будет выбираться с вероятностью p, а “1” - с вероятностью 1-p). Далее число 0 будет означать выбор 1-ой (красной) строки/столбца, а число “1” - выбор второй (синей) строки/столбца.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Задание 2</span><span style=\" font-size:10pt;\">. Рассмотреть следующие вероятностные стратегии игроков: оба игрока равновероятно (с вероятностью ½) выбирают одну или другую строку/столбец.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">   1. Провести 100 экспериментов и сохранить вектор из 100 пар бинарных чисел, соответствующих результатам случайного выбора строк/столбцов.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">   2. Найти выигрыш/проигрыш игрока A (проигрыш/выигрыш игрока B) в проведенном эксперименте. Найти его среднее значение в одной игре.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">   3. Найти математическое ожидание этой величины (теоретическую оценку выигрыша/проигрыша).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">   4. Найти среднее квадратичное отклонение от экспериментального среднего в проведенном эксперименте.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">   5. Найти дисперсию и теоретическое среднее квадратичное отклонение для данных вероятностей.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Задание 3</span><span style=\" font-size:10pt;\">. Рассмотреть следующие вероятностные стратегии игроков:  игрок A равновероятно выбирает строку, а игрок B (случайно) выбирает красный столбец втрое реже, чем синий. И провести полный цикл исследования, как это описано в предыдущем задании.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Задание 4</span><span style=\" font-size:10pt;\">.  Рассмотреть разные методы “машинного обучения” игрока A при условии, что игрок B придерживается стратегии, описанной в предыдущем задании.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">   1. Первый метод: обучение с подкреплением. Для его реализации нужно использовать генератор случайных чисел с переменной границей. Образно этот генератор можно описать так (см. рисунок выше): в коробке у игрока A лежат 10 красных и 10 синих шаров. Он вынимает случайно один шар и выбирает строку, соответствующую цвету шара. После этого в случае выигрыша помещает дополнительные шары того же цвета в количестве равном выигрышу в свою коробку (это соответствует изменению границы p в датчике случайных чисел). В нашем примере это всегда 2 шара.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Для обучения игрока проводятся 100 игр. По полученным после проведения 100 игр вероятностям выбора строки игроком A вычисляются все характеристики задания 2 (понятно, что легче запрограммировать эти вычисления сразу в задании 2).</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">   2. Второй метод: обучение с наказанием. В коробке около игрока A лежит 100 красных и 100 синих шаров. Он вынимает случайно один шар и выбирает строку, соответствующую цвету шара. После этого в случае проигрыша удаляет шары того же цвета из своей коробки по количеству проигрыша (1 или 3 шара). После этого проводится эксперимент из 100 игр и вычисляются все характеристики задания 2.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">   3. Рассмотреть обучение обоих игроков с подкреплением. В коробках около игроков A и B лежат по 10 красных и 10 синих шаров. Далее они поочередно вынимают случайно по шару из своих коробок и выбирают строку (столбец), соответствующие цветам шаров. После этого в случае выигрыша помещают дополнительные шары того же цвета  в количестве равном выигрышу в свою коробку и не меняют содержимого своей коробки при проигрыше. После этого проводится обучающий эксперимент из 100 игр и вычисляются все характеристики задания 2.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Задание 5</span><span style=\" font-size:10pt;\">.  Провести анализ полученных выше результатов. Выдвинуть гипотезы о “правильных” стратегиях игроков. Является ли игра честной? Кто будет побеждать в этой игре? Каков максимальный выигрыш победителя при правильной игре соперника?</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Задание 6</span><span style=\" font-size:10pt;\">.  *Провести аналитические вычисления. Применить сведения из алгебры и анализа для того, чтобы найти оптимальные стратегии игроков.</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "OK"))
