# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rules.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rules(object):
    def setupUi(self, rules):
        rules.setObjectName("rules")
        rules.resize(500, 300)
        rules.setMinimumSize(QtCore.QSize(500, 300))
        rules.setMaximumSize(QtCore.QSize(500, 300))
        rules.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        rules.setStyleSheet("background-color: #fcfeff")
        self.pushButton = QtWidgets.QPushButton(rules)
        self.pushButton.setGeometry(QtCore.QRect(180, 240, 160, 40))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(rules)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 480, 210))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(rules)
        QtCore.QMetaObject.connectSlotsByName(rules)

    def retranslateUi(self, rules):
        _translate = QtCore.QCoreApplication.translate
        rules.setWindowTitle(_translate("rules", "Rules"))
        self.pushButton.setText(_translate("rules", "OK"))
        self.textBrowser.setHtml(_translate("rules", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:11pt; color:#000000;\">Игроки A и B играют в следующую игру. Они одновременно выбирают:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial\'; font-size:11pt; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:11pt; color:#000000;\">     игрок A - строку;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:11pt; color:#000000;\">     игрок B - столбец.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:11pt; color:#000000;\">     Далее они смотрят на пересечение выбранной строки и выбранного столбца.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial\'; font-size:11pt; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:11pt; color:#000000;\">Положительное число на пересечении выбранных строки и столбца показывает выигрыш игрока A и соответствующий проигрыш игрока B, который как бы передает игроку A указанное число денег (в нашем примере это всегда 2 рубля).</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial\'; font-size:11pt; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:11pt; color:#000000;\">Отрицательное число, наоборот, показывает проигрыш игрока A и соответствующий выигрыш B, которому A  передает указанное число денег (в нашем примере это или 1 рубль или 3 рубля).</span></p></body></html>"))
